### ISSUE TITLE
Readme and Documentation Update

### ISSUE THREAD

**Issue by mohitchandak** [Rutuj-Runwal/easynotes#4]
Following on the previous issue #3 will like to enhance the readme to reflect the tech stack used, and add product images

**Comment by mohitchandak** [comment]
Please assign @Rutuj-Runwal

**Comment by Rutuj-Runwal** [comment]
Yes sure go ahead

**Comment by ayushsarode** [comment]
can you assign me please?

**Comment by Rutuj-Runwal** [comment]
> can you assign me please?

Yes you can go ahead and start working

**Comment by Rutuj-Runwal** [comment]
@AyushSarode kindly check your PR #6  I have added mentioned few things that needs to be addressed

**Comment by ayushsarode** [comment]
> @AyushSarode kindly check your PR #6 I have added mentioned few things that needs to be addressed
Please Can you tell me what wrong is going on with that PR
?

**Comment by Rutuj-Runwal** [comment]
> > @AyushSarode kindly check your PR #6 I have added mentioned few things that needs to be addressed
> Please Can you tell me what wrong is going on with that PR
> ?
> 

I already mentioned it in your PR #6 but still this is the change:

Remove the "Thank you" at the end. You can instead add something meaningful like how to build/setu the application inorder to run it.

Do the above change for it to be mergeable

**Comment by ayushsarode** [comment]
Sure! Gonna work on it and also I'm newbie, can you tell me where you mentioned it, like how to find. I tried but can't get on it.

**Comment by Rutuj-Runwal** [comment]
> Sure! Gonna work on it and also I'm newbie, can you tell me where you mentioned it, like how to find. I tried but can't get on it.
> 

Yaa no problem I am always here to help.
If you open the pull request that you had sent and scroll down a bit you will see too comments from me. Expand them and those are the "reviews". They are used to indicate developers if the code requires changes etc ..
Click the below hashtag to see the pull request(Every pull request and issue has a unique tag number so it can be linked and referenced)👇🏻

#6

**Comment by ayushsarode** [comment]
![Screenshot 2022-10-03 010433](https://user-images.githubusercontent.com/72145248/193472861-73684ce1-797b-494a-b111-10390aa7c1cf.png)

There are only two things from you.

**Comment by Rutuj-Runwal** [comment]
> ![Screenshot 2022-10-03 010433](https://user-images.githubusercontent.com/72145248/193472861-73684ce1-797b-494a-b111-10390aa7c1cf.png)
> 
> There are only two things from you.

Can you show full screenshot
Guide karne me it will be easier

**Comment by ayushsarode** [comment]
Thanks for your precise time though! Working on my PR btw.
![Screenshot 2022-10-03 011133](https://user-images.githubusercontent.com/72145248/193473126-23f8bcdc-a30a-44b6-8d4b-4a1546e905c5.png)

**Comment by Rutuj-Runwal** [comment]
> Thanks for your precise time though! Working on my PR btw.
> ![Screenshot 2022-10-03 011133](https://user-images.githubusercontent.com/72145248/193473126-23f8bcdc-a30a-44b6-8d4b-4a1546e905c5.png)
> 

If you click on the "Files changed" and scroll through it you can see the comments

**Comment by ayushsarode** [comment]
![Screenshot 2022-10-03 012054](https://user-images.githubusercontent.com/72145248/193473465-9a063287-953c-48af-88a1-945019ee285f.png)
![Screenshot 2022-10-03 011850](https://user-images.githubusercontent.com/72145248/193473472-feda02f2-9d34-4b5e-8e17-5ba757f9949c.png)

**Comment by Rutuj-Runwal** [comment]
> ![Screenshot 2022-10-03 012054](https://user-images.githubusercontent.com/72145248/193473465-9a063287-953c-48af-88a1-945019ee285f.png)
> ![Screenshot 2022-10-03 011850](https://user-images.githubusercontent.com/72145248/193473472-feda02f2-9d34-4b5e-8e17-5ba757f9949c.png)
> 

I think a bug in.repository configuration is not letting the reviews show. Thank you for providing the ss will fix this problem quickly till then you can start with pr changes are already mentioned in this dicussion

**Comment by ayushsarode** [comment]
Sure! Thank you.

**Comment by AyushSarode** [comment]
hey @Rutuj-Runwal !
Can I ask a doubt about my repo?

**Comment by Rutuj-Runwal** [comment]
> hey @Rutuj-Runwal ! Can I ask a doubt about my repo?

Don't create clutter here you can send your whatsapp number or github repo we can discuss there

**Comment by AyushSarode** [comment]
What About Discord?

**Comment by Rutuj-Runwal** [comment]
> What About Discord?
> 

Works send it here then delete all the  messages that are not related to the issue after wards as they are moderated by hacktonerfest so....

**Comment by AyushSarode** [comment]
Ayush S #7893
